/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz.view;

/**
 *
 * @author luanc
 */
public class TelaDoUsuarioADM extends javax.swing.JFrame {

    /**
     * Creates new form TelaDoUsuarioADM
     */
    public TelaDoUsuarioADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        criarJogo = new javax.swing.JButton();
        jogosSalvos = new javax.swing.JButton();
        informacoes = new javax.swing.JButton();
        ranking = new javax.swing.JButton();
        criarQuestão = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página do Usuário");

        titulo.setFont(new java.awt.Font("Footlight MT Light", 0, 20)); // NOI18N
        titulo.setText("Página do Usuário");

        criarJogo.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        criarJogo.setText("Criar Jogo");

        jogosSalvos.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jogosSalvos.setText("Jogos Salvos");

        informacoes.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        informacoes.setText("Informações");

        ranking.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        ranking.setText("Ranking");

        criarQuestão.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        criarQuestão.setText("Criar Questão");

        sair.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        sair.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jogosSalvos)
                            .addComponent(criarJogo)
                            .addComponent(informacoes)
                            .addComponent(ranking)
                            .addComponent(criarQuestão)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sair)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titulo)
                .addGap(27, 27, 27)
                .addComponent(criarJogo)
                .addGap(18, 18, 18)
                .addComponent(jogosSalvos)
                .addGap(18, 18, 18)
                .addComponent(informacoes)
                .addGap(18, 18, 18)
                .addComponent(ranking)
                .addGap(18, 18, 18)
                .addComponent(criarQuestão)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoUsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoUsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoUsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoUsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoUsuarioADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarJogo;
    private javax.swing.JButton criarQuestão;
    private javax.swing.JButton informacoes;
    private javax.swing.JButton jogosSalvos;
    private javax.swing.JButton ranking;
    private javax.swing.JButton sair;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
